


require('nd-plugins.nd-plugins-list')

require('nd-plugins.nd-builtin.init')
require('nd-plugins.nd-nvimtree.init')
require('nd-plugins.nd-autocommands.init')
require('nd-plugins.nd-colorscheme.nd-base16.init')
require('nd-plugins.nd-colorizer.init')
require('nd-plugins.nd-galaxyline.lines.bubbles')
-- require('nd-plugins.nd-comment.init')
-- require('nd-plugins.nd-compe.init')
-- require('nd-plugins.nd-noclc.init')
require('nd-plugins.nd-vsnip.init')
-- require('nd-plugins.nd-undotree.init')
-- require('nd-plugins.nd-dap.init')
-- require('nd-plugins.nd-dapinstall.init')
require('nd-plugins.nd-lspcolors.init')
-- require('nd-plugins.nd-todocomments.init')
-- require('nd-plugins.nd-trouble.init')
-- require('nd-plugins.nd-lightbulb.init')
-- require('nd-plugins.nd-comfortablemotion.init')
require('nd-plugins.nd-bufferline.init')
require('nd-plugins.nd-dashboard.init')
require('nd-plugins.nd-telescope.init')
require('nd-plugins.nd-gitsigns.init')
-- require('nd-plugins.nd-truezen.init2')
-- require('nd-plugins.nd-limelight.init')
-- require('nd-plugins.nd-rainbow.init')
-- require('nd-plugins.nd-highstr.init')
require('nd-plugins.nd-closebuffers.init')
-- require('nd-plugins.nd-treesitter.init')
-- require('nd-plugins.nd-autopairs.init')
require('nd-plugins.nd-rnvimr.init')
-- require('nd-plugins.nd-tagbar.init')
-- require('nd-plugins.nd-indentblankline.init')

-- For some reason default mappigns can't be disabled from that file. They are now under nd-mappings/_windows
-- require('nd-plugins.nd-vvm.init')

